### ISSUE TITLE
Use of CRT prohibits usage of derived classes

### ISSUE THREAD

**Issue by Flamefire** [slurps-mad-rips/retain-ptr#5]
Consider the following MWE:

```
class Foo: public sg14::reference_count<Foo>{};
class Bar: public Foo{};
sg14::retain_ptr<Foo> foo;
sg14::retain_ptr<Bar> bar;
```

I would expect this code to compile but as `Bar` does not inherit from `reference_count<Bar>` compilation fails: 

> error: no matching function for call to 'sg14::retain_traits<Bar>::decrement(sg14::retain_ptr<Bar>::pointer)'
> 
>      if (*this) { traits_type::decrement(this->get()); }

The proposal does not seem to explicitly state this (or I missed it) but intrusive pointers can be used for performance reasons too (avoid additional allocations for ref count opposed `shared_ptr`). An actual use case I have does this via a base class that "has" the reference counter and many classes that inherit from it. You can then pass around the base class pointer and cast to derived when required, OR pass around the derived class pointer.

The issue described here prevents this.

Solution would be to NOT use CRTP. Changes are trivial and I don't see any disadvantages. It even makes the usage easier. Maybe rename `sg14::reference_count` to `sg14::reference_counter` or `sg14::reference_counted`

**Comment by indianakernick** [comment]
If there is a disadvantage to moving away from CRTP, (I honestly can’t think of one) it might be possible to templatize the member functions of `retain_traits` so that `retain_traits<Derived>` can receive a `reference_count<Base>` and delegate the call to `retain_traits<Base>`.

Also, @slurps-mad-rips what’s the status of the proposal? Has it been reviewed by the committee? I don’t really know the process of voting something into the standard. Is there a good chance it will make it into C++20?

**Comment by Flamefire** [comment]
Why using the templates at all? I don't see the reason for them. Just use the classes and be done with it

**Comment by indianakernick** [comment]
@Flamefire No templates seems like the obvious solution. Surely there must be a reason for using CRTP.

**Comment by Flamefire** [comment]
I see now why: When deleting you need `T`

What about the following?

```
template <class T>
struct atomic_reference_count {
  friend retain_traits;
protected:
  atomic_reference_count () = default;
private:
  std::atomic<long> count { 1 };
};

template <class T>
struct reference_count {
  friend retain_traits;
protected:
  reference_count () = default;
private:
  long count { 1 };
};

struct retain_traits final {

  template <class T>
  static void increment (atomic_reference_count<T>* ptr) noexcept {
    ptr->count.fetch_add(1, std::memory_order::relaxed);
  }

  template <class T>
  static void decrement (atomic_reference_count<T>* ptr) noexcept {
    ptr->count.fetch_sub(1, std::memory_order_acq_rel);
    if (not use_count(ptr)) { delete static_cast<T*>(ptr); }
  }

  template <class T>
  static long use_count (atomic_reference_count<T>* ptr) noexcept {
    return ptr->count.load(std::memory_order::relaxed);
  }

  template <class T>
  static void increment (reference_count<T>* ptr) noexcept { ++ptr->count; }
  template <class T>
  static void decrement (reference_count<T>* ptr) noexcept {
    if (ptr->count -= 1) { delete static_cast<T*>(ptr); }
  }
  template <class T>
  static long use_count (reference_count<T>* ptr) noexcept {
    return ptr->count;
  }
};
```

**Comment by indianakernick** [comment]
Well, that seems to solve it

**Comment by bruxisma** [comment]
Hi, sorry for the delay in responding. I've had a lot of personal life events get in the way this past week.

As some of you have figured out I chose CRTP so we don't need to rely on a virtual destructor. However, @Flamefire you've posted a better implementation. If you would like to submit this as a pull request I would merge it and (with your permission) add an acknowledgement for your help in the R2 for Kona. My only request is to keep the `retain_traits<T>` signature, and use a check for `is_base_of_v`. Users should be permitted to specialize `retain_traits` and this can't be done if the template signature is removed.

> Also, @slurps-mad-rips what’s the status of the proposal? Has it been reviewed by the committee? I don’t really know the process of voting something into the standard. Is there a good chance it will make it into C++20?

Unfortunately, while I've been arguing to get `retain_ptr` in for C++20 *along with* `out_ptr` (as they have the same approach) they were pushed back at San Diego for C++23. However, during a zombie session, `out_ptr` was recommended for C++20. There's a chance now that C++20 will have `out_ptr` and `retain_ptr` will be in C++23. If you have access to the reflector, I recommend mailing the LEWG chair regarding this and requesting it be put in at the same time as `out_ptr`. The LEWGI chair purposefully focused on delaying this proposal, only to walk back this approach as the week continued. If this sounds infuriating or vexing, you bet your ass it was.

The primary arguments right now are that some people feel that the default action for `retain_ptr` should be `retain_object_t`, and not `adopt_object_t`. In my personal opinion, I think this argument is a waste of time, because someone can just do a type alias over a different traits type for each action. I've also heard several other authors being told to explore ADL. I have no intention of doing so and will tell the committee as such if they request it at Kona (assuming `retain_ptr` gets any review and forwarded to LWG)

**Comment by Flamefire** [comment]
I opened #6 implementing this. But I'm concerned about template bloat. One could make `detail` classes of `*reference_count` which do not have template params and public classes which have. The `increment, decrement, use_count` functions could then use these bases classes as params. Then use a deleter function which operates on the templatized version and does the cast.

**Comment by bruxisma** [comment]
@Flamefire thank you. One thing I'd like people to realize is that the requirement for getting something added to the C++ stdlib is that an implementation is required as a proof of concept, but is not required to be high performance unless its argument is that it is faster than an existing implementation. Details such as the one you've mentioned about template bloat is something that vendors can worry about.

(And if the above seems like a dismissal, it's actually me trying to cover my ass because I only use this type for wrapping C libraries with internal reference counts, and only provided the `[atomic_]reference_count` classes as an upgrade path for `boost::intrusive_ptr` users 😅)

**Comment by Flamefire** [comment]
Sure. It is just worth noting this fact especially when you go from `class<T>::foo()` to `class<T>::foo<U>()`

And whether or not this might be included in the C++ standard people might still want to use this in their projects. Maybe even propose this for Boost.SmartPtr so people can use this with older standards or if it won't be included at all.
